# Generated by Django 6.1 on 2026-08-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('sender', models.CharField(default='Website Customer', max_length=255)),
                ('sender_initial', models.CharField(default='C', max_length=5)),
                ('sender_color', models.CharField(default='#3b82f6', max_length=20)),
                ('body', models.TextField()),
                ('full_body', models.TextField(blank=True, null=True)),
                ('recipients', models.CharField(default='Admin Team', max_length=100)),
                ('department', models.CharField(default='Storefront', max_length=100)),
                ('category_badge', models.CharField(default='Notification', max_length=100)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
