# Generated by Django 6.1 on 2026-08-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_order_status_alter_order_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Moxie', max_length=200)),
                ('store_email', models.EmailField(default='support@moxie.com', max_length=254)),
                ('store_phone', models.CharField(default='+91 9876543210', max_length=50)),
                ('store_address', models.TextField(default='123 Moxie Studio, Tech Park, Chennai, Tamil Nadu')),
                ('store_description', models.TextField(default='Moxie E-Commerce - Premium Lifestyle & Fashion Products')),
                ('website_url', models.URLField(default='https://moxie.com')),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('store_status', models.CharField(choices=[('Open', 'Open'), ('Maintenance', 'Maintenance')], default='Open', max_length=20)),
                ('allow_registration', models.BooleanField(default=True)),
                ('allow_guest_browsing', models.BooleanField(default=True)),
                ('require_login_before_checkout', models.BooleanField(default=True)),
                ('allow_reviews', models.BooleanField(default=True)),
                ('allow_wishlist', models.BooleanField(default=True)),
                ('enable_product_search', models.BooleanField(default=True)),
                ('order_prefix', models.CharField(default='MOX', max_length=20)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('max_order_amount', models.DecimalField(decimal_places=2, default=100000.0, max_digits=10)),
                ('allow_order_cancellation', models.BooleanField(default=True)),
                ('allow_returns', models.BooleanField(default=True)),
                ('enable_shipping', models.BooleanField(default=True)),
                ('free_shipping', models.BooleanField(default=True)),
                ('free_shipping_min_amount', models.DecimalField(decimal_places=2, default=999.0, max_digits=10)),
                ('default_shipping_charge', models.DecimalField(decimal_places=2, default=100.0, max_digits=10)),
                ('processing_time', models.CharField(default='1-3 Days', max_length=50)),
                ('delivery_estimate', models.CharField(default='3-7 Days', max_length=50)),
                ('enable_tax', models.BooleanField(default=False)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('tax_included', models.BooleanField(default=True)),
                ('notify_order_created', models.BooleanField(default=True)),
                ('notify_payment_success', models.BooleanField(default=True)),
                ('notify_order_shipped', models.BooleanField(default=True)),
                ('notify_order_delivered', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
