# Generated by Django 6.1 on 2026-09-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_add_admin_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('registration', 'New Customer Registration'), ('login', 'Customer Login'), ('order', 'New Order'), ('order_status', 'Order Status Change'), ('review', 'New Product Review'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock'), ('product_created', 'Product Added'), ('product_updated', 'Product Updated'), ('contact_message', 'Customer Contact Message'), ('system', 'System Announcement'), ('admin_user_created', 'Admin User Created'), ('admin_user_updated', 'Admin User Updated'), ('admin_user_deleted', 'Admin User Deleted')], default='system', max_length=50),
        ),
    ]
