# Generated by Django 6.1 on 2026-09-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_adminprofile_permissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='raw_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
