# Generated by Django 6.1 on 2026-09-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_adminprofile_raw_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminprofile',
            name='raw_password',
        ),
    ]
