# Generated by Django 6.1 on 2026-09-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_adminprofile_raw_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='raw_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
