# Generated by Django 6.1 on 2026-09-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_offer_discount_value_offer_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='admin/profiles/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='allow_guest_checkout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='allow_order_modification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='auto_confirm_orders',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='cancellation_time_limit',
            field=models.CharField(default='24 Hours', max_length=50),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='city',
            field=models.CharField(default='Chennai', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='cod_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='cod_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='delivery_area',
            field=models.CharField(default='All India (Pan India)', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='enable_order_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='enable_order_tracking',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='enable_stock_management',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='express_delivery_days',
            field=models.CharField(default='1-2 Days', max_length=50),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='express_shipping_charge',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='gst_number',
            field=models.CharField(default='33AAAAA0000A1Z5', max_length=50),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='low_stock_alert',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='min_stock_threshold',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='notify_low_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='notify_new_customer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='notify_order_cancelled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='notify_order_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='online_payment_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='order_auto_cancel_time',
            field=models.CharField(default='48 Hours', max_length=50),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='payment_currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='payment_mode',
            field=models.CharField(default='Test', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='payment_timeout',
            field=models.CharField(default='15 Minutes', max_length=50),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='pincode',
            field=models.CharField(default='600001', max_length=20),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='razorpay_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='shipping_provider',
            field=models.CharField(default='Delhivery / Bluedart', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='smtp_from_email',
            field=models.CharField(default='noreply@moxie.com', max_length=200),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='smtp_host',
            field=models.CharField(default='smtp.gmail.com', max_length=200),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='smtp_port',
            field=models.IntegerField(default=587),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='smtp_user',
            field=models.CharField(default='support@moxie.com', max_length=200),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='state',
            field=models.CharField(default='Tamil Nadu', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='store_logo',
            field=models.ImageField(blank=True, null=True, upload_to='settings/logos/'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='tax_name',
            field=models.CharField(default='GST (Goods & Services Tax)', max_length=100),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='tax_type',
            field=models.CharField(default='GST', max_length=50),
        ),
        migrations.AlterField(
            model_name='storesettings',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
    ]
