# Generated by Django 6.1 on 2026-09-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_adminpasswordresetotp_adminpasswordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_decremented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
