# Generated by Django 6.1 on 2026-09-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_order_shipping_fee_order_subtotal_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storesettings',
            name='require_login_before_checkout',
            field=models.BooleanField(default=False),
        ),
    ]
