# Generated by Django 6.1 on 2026-09-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_storesettings_require_login_before_checkout'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='google_sub',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
