# Generated by Django 6.1 on 2026-09-15 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_order_amount_paid_order_balance_due_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carrier_status_raw',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='tracking_receipts/'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_source',
            field=models.CharField(choices=[('ADMIN', 'Manual Admin'), ('CARRIER_API', 'Carrier API')], default='ADMIN', max_length=30),
        ),
        migrations.AddField(
            model_name='orderstatushistory',
            name='source',
            field=models.CharField(default='ADMIN', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Processing', 'Processing'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], default='Pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('SMS', 'SMS')], default='WHATSAPP', max_length=20)),
                ('message_type', models.CharField(choices=[('ORDER_CONFIRMED', 'Order Confirmed'), ('SHIPPED', 'Order Shipped'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Order Delivered'), ('CANCELLED', 'Order Cancelled')], max_length=50)),
                ('recipient', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('payload_summary', models.TextField(blank=True, default='')),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_message', models.TextField(blank=True, default='')),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='api.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
