# Generated by Django 6.1 on 2026-09-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_order_carrier_status_raw_order_out_for_delivery_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='customer/profiles/'),
        ),
    ]
