# Generated by Django 6.1 on 2026-09-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_customerprofile_avatar_customerprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='emoji',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
