# Generated by Django 6.1 on 2026-09-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_offer_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_locked',
            field=models.BooleanField(default=False),
        ),
    ]
