export {
  DashboardSquare01Icon as DashboardIcon,
  PackageIcon as ProductIcon,
  Layers01Icon as CategoryAdminIcon,
  Folder01Icon as FolderIcon,
  ShoppingBag01Icon as OrderIcon,
  UserGroupIcon as CustomersIcon,
  Comment01Icon as ReviewIcon,
  Comment01Icon as MessageIcon,
  Image01Icon as BannerIcon,
  Image01Icon as ImageIcon,
  Tag01Icon as OfferAdminIcon,
  Analytics01Icon as AnalyticsIcon,
  ChartLineData01Icon as ChartIcon,
  BarChartIcon,
  CreditCardIcon as PaymentIcon,
  DeliveryTruck01Icon as ShippingIcon,
  Notification01Icon as NotificationIcon,
  BellIcon,
  Settings01Icon as SettingsIcon,
  Settings02Icon,
  Logout01Icon as LogoutIcon,
  Shield01Icon as SecurityIcon,
  Building01Icon as BuildingIcon,
  Discount01Icon as ReceiptIcon,
  Mail01Icon as MailIcon,
  Database01Icon as DatabaseIcon,
} from "@hugeicons/core-free-icons";

