# Generated by Django 6.1 on 2026-09-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_review_email_review_is_verified_review_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sizes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
