# Generated by Django 6.1 on 2026-09-15 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_shipping_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('HOT_SALE', 'Hot Sale'), ('TRENDING', 'Trending'), ('OFFER', 'Offer')], default='HOT_SALE', max_length=20)),
                ('display_image', models.ImageField(blank=True, null=True, upload_to='featured_products/')),
                ('badge_text', models.CharField(blank=True, max_length=50)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_entries', to='products.product')),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
                'unique_together': {('product', 'feature_type')},
            },
        ),
    ]
