export {
  Add01Icon as PlusIcon,
  Add01Icon as PlusSignIcon,
  MinusSignIcon as MinusIcon,
  MinusSignIcon,
  Edit01Icon as EditIcon,
  Edit01Icon,
  Edit02Icon,
  TrashIcon as DeleteIcon,
  TrashIcon as Delete02Icon,
  TrashIcon,
  SaveIcon,
  Cancel01Icon as CancelIcon,
  Cancel01Icon,
  Cancel02Icon,
  CancelCircleIcon,
  EyeIcon as ViewIcon,
  EyeIcon,
  EyeOffIcon as ViewOffSlashIcon,
  EyeOffIcon as HideIcon,
  EyeOffIcon,
  LockIcon,
  LockOpenIcon as UnlockIcon,
  Upload01Icon as UploadIcon,
  Download01Icon as DownloadIcon,
  FilterIcon,
  SortByDown01Icon as SortingIcon,
  SortByDown01Icon as SortIcon,
  Copy01Icon as CopyIcon,
  MoreHorizontalIcon,
  QuoteDownIcon,
  QuoteUpIcon,
  CustomerSupportIcon,
  CheckmarkCircle01Icon as CheckIcon,
  CheckmarkCircle02Icon,
} from "@hugeicons/core-free-icons";
