export {
  ShoppingBag01Icon as ShoppingBagIcon,
  ShoppingBag01Icon as BagIcon,
  ShoppingCart01Icon as ShoppingCartIcon,
  ShoppingCart01Icon as CartIcon,
  FavouriteIcon as HeartIcon,
  FavouriteIcon as WishlistIcon,
  PackageIcon,
  DeliveryTruck01Icon as DeliveryTruckIcon,
  DeliveryTruck01Icon as TruckIcon,
  CreditCardIcon,
  Tag01Icon as TagIcon,
  Discount01Icon as DiscountIcon,
  PercentCircleIcon as PercentIcon,
  BadgePercentIcon,
  StarIcon,
  SparklesIcon,
  FlashIcon,
  FireIcon,
  Award01Icon as AwardIcon,
  Invoice01Icon as InvoiceIcon,
  RotateLeft01Icon as ReturnIcon,
  Store01Icon as StoreIcon,
} from "@hugeicons/core-free-icons";
