# Generated by Django 6.1 on 2026-09-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_cleanup_demo_banners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.FileField(upload_to='banners/'),
        ),
    ]
